# Generated by Django 6.1.1 on 2026-09-30 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=False)),
                ('mensaje', models.CharField(blank=True, help_text='Lo que ven los usuarios. Si se deja vacío se muestra un mensaje genérico.', max_length=300)),
                ('vuelve_aprox', models.CharField(blank=True, help_text='Opcional. Ej: "a las 15:30" o "en 20 minutos".', max_length=60, verbose_name='vuelve aproximadamente')),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'estado de mantenimiento',
                'verbose_name_plural': 'estado de mantenimiento',
            },
        ),
    ]
