# Generated by Django 6.1.1 on 2026-10-04 17:14

import django.db.models.deletion
import django.db.models.manager
import reventa.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='modificado')),
                ('eliminado_en', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='eliminado')),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='teléfono')),
                ('notas', models.TextField(blank=True)),
                ('codigo', models.CharField(default=reventa.models._codigo_nuevo, editable=False, max_length=8, unique=True, verbose_name='código de acceso')),
                ('pantallas', models.PositiveSmallIntegerField(default=1, help_text='Cuántos dispositivos a la vez. Se aplica desde la próxima renovación.')),
                ('vence', models.DateTimeField(blank=True, help_text='Hasta cuándo puede ver. Vacío = nunca se activó.', null=True)),
                ('suspendido', models.BooleanField(default=False, help_text='Cortarle el servicio aunque no haya vencido.')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('eliminado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por')),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['nombre'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('todos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='modificado')),
                ('eliminado_en', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='eliminado')),
                ('nombre', models.CharField(max_length=80)),
                ('creditos', models.PositiveIntegerField(verbose_name='créditos')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('activo', models.BooleanField(default=True, help_text='Un paquete inactivo no se puede comprar.')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('eliminado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por')),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
            ],
            options={
                'verbose_name': 'paquete de créditos',
                'verbose_name_plural': 'paquetes de créditos',
                'ordering': ['creditos'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('todos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creditos', models.PositiveIntegerField(verbose_name='créditos')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de pago'), ('pagada', 'Pagada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=10)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('resuelta', models.DateTimeField(blank=True, null=True, verbose_name='pagada / cancelada')),
                ('pedida_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('resuelta_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('paquete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to='reventa.paquete')),
            ],
            options={
                'verbose_name': 'compra de créditos',
                'verbose_name_plural': 'compras de créditos',
                'ordering': ['-creada'],
            },
        ),
        migrations.CreateModel(
            name='Renovacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pantallas', models.PositiveSmallIntegerField()),
                ('periodos', models.PositiveSmallIntegerField(default=1, verbose_name='períodos de 30 días')),
                ('creditos', models.PositiveIntegerField(verbose_name='créditos usados')),
                ('monto_cobrado', models.DecimalField(decimal_places=2, default=0, help_text='Lo que el revendedor le cobró (para calcular su ganancia).', max_digits=12, verbose_name='cobrado al cliente')),
                ('desde', models.DateTimeField()),
                ('hasta', models.DateTimeField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='renovaciones', to='reventa.cliente')),
                ('hecha_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'renovación',
                'verbose_name_plural': 'renovaciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Revendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='modificado')),
                ('eliminado_en', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='eliminado')),
                ('precio_pantalla', models.DecimalField(decimal_places=2, default=0, help_text='Lo que cobra a sus clientes por cada pantalla, cada 30 días. Se propone solo al renovar.', max_digits=12, verbose_name='precio por pantalla')),
                ('notas', models.TextField(blank=True, help_text='Solo las ve el administrador.')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('eliminado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por')),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='revendedor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'revendedor',
                'verbose_name_plural': 'revendedores',
                'ordering': ['usuario__first_name', 'usuario__last_name', 'usuario__username'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('todos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(help_text='Positivo = entran créditos; negativo = salen.')),
                ('tipo', models.CharField(choices=[('regalo', 'Créditos regalados'), ('compra', 'Compra de paquete'), ('renovacion', 'Activación / renovación de cliente'), ('ajuste', 'Ajuste del administrador')], max_length=12)),
                ('detalle', models.CharField(blank=True, max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('compra', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimiento', to='reventa.compra')),
                ('hecho_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('renovacion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimiento', to='reventa.renovacion')),
                ('revendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='reventa.revendedor')),
            ],
            options={
                'verbose_name': 'movimiento de créditos',
                'verbose_name_plural': 'movimientos de créditos',
                'ordering': ['-fecha', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='compra',
            name='revendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='reventa.revendedor'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='revendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='reventa.revendedor'),
        ),
    ]
