# Generated by Django 6.1.1 on 2026-10-04 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reventa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='revendedor',
            field=models.ForeignKey(blank=True, help_text='Vacío = cliente directo (no gasta créditos).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='reventa.revendedor'),
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_hash', models.CharField(max_length=64, unique=True)),
                ('nombre', models.CharField(blank=True, help_text='Ej: "Smart TV Philips". Lo informa la app.', max_length=100)),
                ('conectado', models.DateTimeField(auto_now_add=True, verbose_name='conectado desde')),
                ('ultima_senal', models.DateTimeField(verbose_name='última señal')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='reventa.cliente')),
            ],
            options={
                'verbose_name': 'dispositivo conectado',
                'verbose_name_plural': 'dispositivos conectados',
                'ordering': ['-ultima_senal'],
            },
        ),
    ]
