# Generated by Django 6.1.1 on 2026-10-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reventa', '0002_dispositivos_y_clientes_directos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='pantallas',
        ),
        migrations.RemoveField(
            model_name='renovacion',
            name='periodos',
        ),
        migrations.AlterField(
            model_name='renovacion',
            name='pantallas',
            field=models.PositiveSmallIntegerField(verbose_name='dispositivos'),
        ),
        migrations.AlterField(
            model_name='revendedor',
            name='precio_pantalla',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Lo que cobra a sus clientes por cada dispositivo, cada 30 días. Se propone solo al renovar.', max_digits=12, verbose_name='precio por dispositivo'),
        ),
    ]
