# Generated by Django 6.1.1 on 2026-10-06 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reventa', '0003_clientes_sin_pantallas_fijas'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='propio',
            field=models.BooleanField(default=False, verbose_name='pantalla propia del revendedor'),
        ),
    ]
