# Generated by Django 6.1.1 on 2026-10-02 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_hash', models.CharField(max_length=64, unique=True)),
                ('dispositivo', models.CharField(blank=True, help_text='Ej: "Samsung A54". Lo informa la app.', max_length=100)),
                ('huella_password', models.CharField(max_length=128)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('ultimo_uso', models.DateTimeField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_api', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'token de acceso',
                'verbose_name_plural': 'tokens de acceso',
                'ordering': ['-ultimo_uso'],
            },
        ),
    ]
