# Generated by Django 6.1.1 on 2026-10-04 15:55

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='modificado')),
                ('eliminado_en', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='eliminado')),
                ('nombre', models.CharField(max_length=80)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Menor = aparece primero.')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('eliminado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por')),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['orden', 'nombre'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('todos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Canal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='modificado')),
                ('eliminado_en', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='eliminado')),
                ('nombre', models.CharField(max_length=120)),
                ('numero', models.CharField(blank=True, help_text='Número de canal (ej: 26).', max_length=10, verbose_name='número')),
                ('logo', models.URLField(blank=True, help_text='Dirección de la imagen del logo.', max_length=500)),
                ('tvg_id', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='ID de guía (tvg-id)')),
                ('pais', models.CharField(blank=True, help_text='Código de 2 letras (AR, UY...).', max_length=2, verbose_name='país')),
                ('activo', models.BooleanField(default=True, help_text='Un canal inactivo no aparece en la app.')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Menor = aparece primero dentro de su categoría.')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('eliminado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por')),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canales', to='canales.categoria', verbose_name='categoría')),
            ],
            options={
                'verbose_name': 'canal',
                'verbose_name_plural': 'canales',
                'ordering': ['orden', 'nombre'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('todos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Fuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000, verbose_name='dirección')),
                ('tipo', models.CharField(choices=[('hls', 'HLS (.m3u8)'), ('youtube', 'YouTube')], default='hls', max_length=10)),
                ('prioridad', models.PositiveIntegerField(default=0, help_text='Menor = se prueba primero.')),
                ('activa', models.BooleanField(default=True)),
                ('origen', models.CharField(blank=True, help_text='De qué lista se importó.', max_length=150)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuentes', to='canales.canal')),
            ],
            options={
                'verbose_name': 'fuente',
                'verbose_name_plural': 'fuentes',
                'ordering': ['prioridad', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.UniqueConstraint(condition=models.Q(('eliminado_en__isnull', True)), fields=('nombre',), name='categoria_nombre_unico'),
        ),
        migrations.AddConstraint(
            model_name='fuente',
            constraint=models.UniqueConstraint(fields=('canal', 'url'), name='fuente_unica_por_canal'),
        ),
    ]
