# Generated by Django 6.1.1 on 2026-10-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuente',
            name='error',
            field=models.CharField(blank=True, max_length=200, verbose_name='motivo de la falla'),
        ),
        migrations.AddField(
            model_name='fuente',
            name='estado',
            field=models.CharField(choices=[('sin_verificar', 'Sin verificar'), ('funciona', 'Funciona'), ('caida', 'Caída')], default='sin_verificar', help_text='Lo pone la verificación automática. La app no usa las caídas.', max_length=15),
        ),
        migrations.AddField(
            model_name='fuente',
            name='verificada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='última verificación'),
        ),
        migrations.AlterField(
            model_name='fuente',
            name='activa',
            field=models.BooleanField(default=True, help_text='Apagarla a mano: la app no la usa aunque funcione.'),
        ),
    ]
