# Generated by Django 6.1.1 on 2026-10-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canales', '0002_estado_de_las_fuentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuente',
            name='referer',
            field=models.CharField(blank=True, help_text='Página desde la que "viene" el pedido, si el canal lo exige.', max_length=500, verbose_name='Referer'),
        ),
        migrations.AddField(
            model_name='fuente',
            name='user_agent',
            field=models.CharField(blank=True, help_text='Solo si el canal lo exige (lo traen algunas listas M3U).', max_length=300, verbose_name='User-Agent'),
        ),
    ]
