# Generated by Django 6.1.1 on 2026-10-05 15:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canales', '0003_cabeceras_de_las_fuentes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='canal',
            name='idioma',
            field=models.CharField(blank=True, choices=[('es', 'Español'), ('otro', 'Otro idioma'), ('', 'No se sabe')], db_index=True, help_text='Estimado al importar (país, categoría, prefijo del nombre...).', max_length=5),
        ),
        migrations.AddField(
            model_name='canal',
            name='motivo_quitado',
            field=models.CharField(blank=True, max_length=200, verbose_name='por qué se quitó'),
        ),
        migrations.AlterField(
            model_name='canal',
            name='activo',
            field=models.BooleanField(default=True, help_text='Un canal inactivo ("quitado") no aparece en la app.'),
        ),
        migrations.AlterField(
            model_name='fuente',
            name='tipo',
            field=models.CharField(choices=[('hls', 'HLS (.m3u8)'), ('dash', 'DASH (.mpd)'), ('directo', 'Video directo (TS, MP4...)'), ('rtsp', 'RTSP'), ('youtube', 'YouTube')], default='hls', max_length=10),
        ),
        migrations.AlterField(
            model_name='fuente',
            name='url',
            field=models.CharField(max_length=1000, validators=[django.core.validators.URLValidator(schemes=['http', 'https', 'rtsp', 'rtsps'])], verbose_name='dirección'),
        ),
        migrations.CreateModel(
            name='Importacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.CharField(max_length=150)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('terminada', models.DateTimeField(blank=True, null=True)),
                ('total', models.PositiveIntegerField(default=0)),
                ('para_verificar', models.PositiveIntegerField(default=0)),
                ('solo_espanol', models.BooleanField(default=False)),
                ('descartar_sin_logo', models.BooleanField(default=False)),
                ('descartar_vod', models.BooleanField(default=True, verbose_name='descartar películas y series')),
                ('descartar_adultos', models.BooleanField(default=True, verbose_name='descartar contenido para adultos')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'importación',
                'verbose_name_plural': 'importaciones',
                'ordering': ['-creada'],
            },
        ),
        migrations.CreateModel(
            name='EntradaImportada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.PositiveIntegerField()),
                ('nombre_original', models.CharField(help_text='Como venía en la lista.', max_length=200)),
                ('nombre', models.CharField(help_text='Limpio: sin prefijo de país ni calidad.', max_length=120)),
                ('logo', models.CharField(blank=True, max_length=500)),
                ('categoria', models.CharField(blank=True, max_length=80)),
                ('numero', models.CharField(blank=True, max_length=10)),
                ('tvg_id', models.CharField(blank=True, max_length=120)),
                ('pais', models.CharField(blank=True, max_length=2)),
                ('idioma', models.CharField(blank=True, choices=[('es', 'Español'), ('otro', 'Otro idioma'), ('', 'No se sabe')], max_length=5)),
                ('contenido', models.CharField(choices=[('vivo', 'En vivo'), ('pelicula', 'Película'), ('serie', 'Serie')], default='vivo', max_length=10)),
                ('url', models.CharField(max_length=1000)),
                ('tipo', models.CharField(blank=True, max_length=10, verbose_name='formato')),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('referer', models.CharField(blank=True, max_length=500)),
                ('estado', models.CharField(choices=[('pendiente', 'Por verificar'), ('agregada', 'Agregada'), ('caida', 'No funciona'), ('descartada', 'Descartada'), ('repetida', 'Ya estaba')], default='pendiente', max_length=12)),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('canal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='canales.canal')),
                ('importacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='canales.importacion')),
            ],
            options={
                'verbose_name': 'entrada importada',
                'verbose_name_plural': 'entradas importadas',
                'ordering': ['posicion'],
                'indexes': [models.Index(fields=['importacion', 'estado', 'posicion'], name='canales_ent_importa_1f662c_idx')],
            },
        ),
    ]
