# Generated by Django 6.1.1 on 2026-10-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canales', '0005_estimar_idioma'),
    ]

    operations = [
        migrations.AddField(
            model_name='canal',
            name='contenido',
            field=models.CharField(choices=[('vivo', 'En vivo'), ('pelicula', 'Película'), ('serie', 'Serie')], db_index=True, default='vivo', max_length=10),
        ),
        migrations.AlterField(
            model_name='fuente',
            name='tipo',
            field=models.CharField(choices=[('hls', 'HLS (.m3u8)'), ('dash', 'DASH (.mpd)'), ('directo', 'Video directo (TS, MP4...)'), ('rtsp', 'RTSP'), ('youtube', 'YouTube'), ('pagina', 'Página de video (Twitch, Dailymotion...)')], default='hls', max_length=10),
        ),
        migrations.AlterField(
            model_name='importacion',
            name='descartar_vod',
            field=models.BooleanField(default=False, verbose_name='descartar películas y series'),
        ),
    ]
