# Generated by Django 6.1.1 on 2026-10-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canales', '0006_contenido_y_paginas'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuente',
            name='avisos_de_aparatos',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fuente',
            name='falla_en_aparatos',
            field=models.CharField(blank=True, max_length=200, verbose_name='motivo según los aparatos'),
        ),
        migrations.AddField(
            model_name='fuente',
            name='oculta_desde',
            field=models.DateTimeField(blank=True, null=True, verbose_name='oculta por fallar en los aparatos desde'),
        ),
        migrations.AddField(
            model_name='fuente',
            name='primer_aviso',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
