# Generated by Django 6.1.1 on 2026-10-06 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canales', '0007_avisos_de_los_aparatos'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuente',
            name='codec',
            field=models.CharField(blank=True, help_text='Lo averigua la verificación.', max_length=10, verbose_name='códec'),
        ),
    ]
