# Generated by Django 6.1.1 on 2026-10-06 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canales', '0008_codec_de_las_fuentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradaimportada',
            name='calidad',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='entradaimportada',
            name='causa',
            field=models.CharField(blank=True, choices=[('formato', 'Formato que muchos aparatos no leen'), ('sin_sonido', 'Sin sonido'), ('idioma', 'Audio en otro idioma'), ('baja_calidad', 'Imagen de baja calidad'), ('lenta', 'Llega lenta (se cortaría)'), ('se_corta', 'Se corta o está congelada'), ('serie_incompleta', 'Serie incompleta')], max_length=16),
        ),
        migrations.AddField(
            model_name='entradaimportada',
            name='codec',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='entradaimportada',
            name='estado_fuente',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='fuente',
            name='calidad',
            field=models.CharField(blank=True, help_text='Lo que encontró la prueba a fondo.', max_length=80),
        ),
        migrations.AddField(
            model_name='importacion',
            name='a_fondo',
            field=models.BooleanField(default=False, verbose_name='prueba a fondo'),
        ),
        migrations.AddField(
            model_name='importacion',
            name='cargada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entradaimportada',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Por probar'), ('apta', 'Apta (falta cargar)'), ('agregada', 'Cargada'), ('caida', 'No responde'), ('rechazada', 'No pasó la prueba'), ('descartada', 'Descartada'), ('repetida', 'Ya estaba')], default='pendiente', max_length=12),
        ),
    ]
