# Generated by Django 6.1.1 on 2026-10-07 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canales', '0009_prueba_a_fondo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoritoAgregado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=130)),
                ('fecha', models.DateField(db_index=True)),
                ('veces', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'favorito agregado',
                'verbose_name_plural': 'favoritos agregados',
                'constraints': [models.UniqueConstraint(fields=('clave', 'fecha'), name='un_favorito_por_clave_y_dia')],
            },
        ),
        migrations.CreateModel(
            name='Visto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('segundos', models.PositiveIntegerField(default=0)),
                ('vistas', models.PositiveIntegerField(default=0, help_text='Veces que alguien lo miró más de un minuto.')),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vistos', to='canales.canal')),
            ],
            options={
                'verbose_name': 'visto',
                'verbose_name_plural': 'vistos',
                'constraints': [models.UniqueConstraint(fields=('canal', 'fecha'), name='un_visto_por_canal_y_dia')],
            },
        ),
    ]
