# Generated by Django 6.1.1 on 2026-10-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canales', '0010_lo_mas_visto'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='otros_nombres',
            field=models.TextField(blank=True),
        ),
    ]
