# Generated by Django 6.1.1 on 2026-10-09 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canales', '0011_otros_nombres_de_categorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuente',
            name='tipo',
            field=models.CharField(choices=[('hls', 'HLS (.m3u8)'), ('dash', 'DASH (.mpd)'), ('directo', 'Video directo (TS, MP4...)'), ('rtsp', 'RTSP'), ('youtube', 'YouTube'), ('pagina', 'Página de video (Twitch, Dailymotion...)'), ('yt_video', 'Video de YouTube (reproductor oficial)')], default='hls', max_length=10),
        ),
    ]
