# Generated by Django 6.1.1 on 2026-10-09 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canales', '0012_video_de_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategorias', to='canales.categoria', verbose_name='dentro de'),
        ),
    ]
