# Generated by Django 6.1.1 on 2026-10-10 03:59

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canales', '0017_importar_como_serie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='importacion',
            name='seccion',
            field=models.CharField(blank=True, max_length=10, verbose_name='sección'),
        ),
        migrations.AlterField(
            model_name='canal',
            name='contenido',
            field=models.CharField(db_index=True, default='vivo', max_length=10),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='contenido',
            field=models.CharField(db_index=True, default='vivo', max_length=10, verbose_name='sección'),
        ),
        migrations.AlterField(
            model_name='entradaimportada',
            name='contenido',
            field=models.CharField(default='vivo', max_length=10),
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='modificado')),
                ('eliminado_en', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='eliminado')),
                ('clave', models.CharField(editable=False, help_text='Se arma del nombre: "Música" -> "musica".', max_length=10)),
                ('nombre', models.CharField(max_length=30)),
                ('forma', models.CharField(choices=[('vivo', 'En vivo (radios o canales que transmiten ahora)'), ('pelicula', 'A demanda (videos que se eligen: música, documentales...)')], default='pelicula', max_length=10)),
                ('icono', models.CharField(choices=[('musica', 'Música'), ('radio', 'Radio'), ('deportes', 'Deportes'), ('documentales', 'Documentales'), ('infantil', 'Infantil'), ('noticias', 'Noticias'), ('otro', 'Otro (una estrella)')], default='otro', max_length=15, verbose_name='ícono')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Menor = más arriba en el menú de la app.')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('eliminado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por')),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
            ],
            options={
                'verbose_name': 'sección',
                'verbose_name_plural': 'secciones',
                'ordering': ['orden', 'nombre'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('eliminado_en__isnull', True)), fields=('clave',), name='seccion_clave_unica')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('todos', django.db.models.manager.Manager()),
            ],
        ),
    ]
