# Generated by Django 6.1.1 on 2026-10-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canales', '0018_secciones_nuevas'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortadaDeSerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=90, unique=True)),
                ('nombre', models.CharField(max_length=90)),
                ('imagen', models.URLField(max_length=500)),
                ('modificada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'portada de serie',
                'verbose_name_plural': 'portadas de series',
            },
        ),
    ]
