# Generated by Django 6.1.1 on 2026-09-30 01:41

import django.contrib.auth.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import usuarios.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('permisos', models.JSONField(blank=True, default=list)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'rol',
                'verbose_name_plural': 'roles',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(help_text='Letras, números y los caracteres @ . + - _', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='nombre de usuario')),
                ('email', models.EmailField(blank=True, help_text='Se usa para iniciar sesión y para recuperar la contraseña.', max_length=254, null=True, verbose_name='email')),
                ('is_active', models.BooleanField(default=True, help_text='Un usuario inactivo no puede iniciar sesión.', verbose_name='activo')),
                ('is_staff', models.BooleanField(default=False, help_text='Solo para el equipo técnico.', verbose_name='acceso al admin de Django')),
                ('debe_cambiar_password', models.BooleanField(default=False, help_text='Se le pide una contraseña nueva al iniciar sesión.', verbose_name='debe cambiar la contraseña')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='nombre/s')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='apellido/s')),
                ('tipo_documento', models.CharField(blank=True, choices=[('dni', 'DNI'), ('cuil_cuit', 'CUIL / CUIT'), ('pasaporte', 'Pasaporte'), ('otro', 'Otro')], max_length=15, verbose_name='tipo de documento')),
                ('numero_documento', models.CharField(blank=True, max_length=30, verbose_name='número de documento')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento')),
                ('genero', models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro'), ('no_informa', 'Prefiere no decir')], max_length=15, verbose_name='género')),
                ('foto', models.ImageField(blank=True, upload_to=usuarios.models._ruta_foto_usuario, verbose_name='foto de perfil')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='teléfono')),
                ('telefono_alternativo', models.CharField(blank=True, max_length=30, verbose_name='teléfono alternativo')),
                ('calle', models.CharField(blank=True, max_length=150)),
                ('numero', models.CharField(blank=True, max_length=20, verbose_name='número')),
                ('piso_depto', models.CharField(blank=True, max_length=30, verbose_name='piso / depto')),
                ('localidad', models.CharField(blank=True, max_length=100)),
                ('provincia', models.CharField(blank=True, max_length=100)),
                ('codigo_postal', models.CharField(blank=True, max_length=15, verbose_name='código postal')),
                ('pais', models.CharField(blank=True, default='Argentina', max_length=100, verbose_name='país')),
                ('emergencia_nombre', models.CharField(blank=True, max_length=150, verbose_name='contacto de emergencia')),
                ('emergencia_telefono', models.CharField(blank=True, max_length=30, verbose_name='teléfono de emergencia')),
                ('puesto', models.CharField(blank=True, max_length=100, verbose_name='puesto / cargo')),
                ('area', models.CharField(blank=True, max_length=100, verbose_name='área')),
                ('fecha_ingreso', models.DateField(blank=True, null=True, verbose_name='fecha de ingreso')),
                ('notas_internas', models.TextField(blank=True, help_text='Solo las ve quien gestiona usuarios, nunca el propio usuario.', verbose_name='notas internas')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de alta')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='última modificación')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='usuarios.rol')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'ordering': ['username'],
            },
            managers=[
                ('objects', usuarios.models.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='CodigoRecuperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_hash', models.CharField(max_length=128)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usado', models.BooleanField(default=False)),
                ('intentos', models.PositiveSmallIntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_recuperacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'código de recuperación',
                'verbose_name_plural': 'códigos de recuperación',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='PermisoIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso', models.CharField(max_length=60)),
                ('concedido', models.BooleanField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_individuales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'permiso individual',
                'verbose_name_plural': 'permisos individuales',
                'constraints': [models.UniqueConstraint(fields=('usuario', 'permiso'), name='permiso_individual_unico')],
            },
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('username'), name='usuario_username_unico_ci', violation_error_message='Ya existe un usuario con ese nombre de usuario.'),
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='usuario_email_unico_ci', violation_error_message='Ya existe un usuario con ese email.'),
        ),
    ]
