# Generated by Django 6.1.1 on 2026-10-04 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='Ej: 1.0.3 (la de pubspec.yaml).', max_length=30, verbose_name='versión')),
                ('archivo', models.FileField(upload_to='apk/', verbose_name='APK')),
                ('notas', models.TextField(blank=True, verbose_name='qué cambió')),
                ('publicada', models.BooleanField(default=True, help_text='Las no publicadas no se descargan.')),
                ('subida', models.DateTimeField(auto_now_add=True)),
                ('subida_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'versión de la app',
                'verbose_name_plural': 'versiones de la app',
                'ordering': ['-subida', '-pk'],
            },
        ),
    ]
