import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..');
const out = path.join(root, 'html');
fs.mkdirSync(out, { recursive: true });

const head = (title) => `<!doctype html>
<html lang="es-AR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>${title} · Kairos TV</title><script src="https://cdn.tailwindcss.com"></script>
<script>tailwind.config={theme:{extend:{colors:{grafito:'#131317',cian:'#00F0FF',rubi:'#DF0041'},fontFamily:{titulo:['Jakarta'],texto:['Inter']}}}}</script>
<link rel="stylesheet" href="../shared/theme.css"></head><body>`;

const sidebar = (active='inicio') => {
  const items = [['inicio','⌂','Inicio'],['vivo','◉','En vivo'],['guia','▤','Guía'],['peliculas','▰','Películas'],['series','▦','Series'],['buscar','⌕','Buscar'],['favoritos','♥','Favoritos']];
  return `<aside class="sidebar glass" aria-label="Menú lateral"><div class="brand-slot logo-ready"><img src="../brand/kairos-tv-symbol.png" alt="Kairos TV"></div>${items.map(([id,ic,label])=>`<div class="nav ${id===active?'active':''}" title="${label}" aria-label="${label}">${ic}</div>`).join('')}<div class="nav grow ${active==='cuenta'?'active':''}" title="Mi cuenta">●</div></aside>`;
};

const tvPage = (title, active, content, note='Prototipo TV · 1920 × 1080') => `${head(title)}<main class="tv relative overflow-hidden bg-[#131317] text-[#E4E1E8]">${sidebar(active)}<div class="spec-note">${note}</div><section class="content">${content}</section></main></body></html>`;
const bareTv = (title, content, note='Prototipo TV · 1920 × 1080') => `${head(title)}<main class="tv relative overflow-hidden bg-[#131317] text-[#E4E1E8]"><div class="spec-note">${note}</div>${content}</main></body></html>`;

const top = (eyebrow,title,right='') => `<header class="topbar"><div style="flex:1"><div class="eyebrow">${eyebrow}</div><h1 style="font-size:34px;margin-top:2px">${title}</h1></div>${right}</header>`;
const live = `<span class="live"><i class="dot"></i>EN VIVO</span>`;
const chips = (active='Todo') => `<div class="row" style="gap:12px"><span class="chip ${active==='Todo'?'active':''}">Todo</span><span class="chip ${active==='Deportes'?'active':''}">Deportes</span><span class="chip">Noticias</span><span class="chip">Infantiles</span><span class="chip">Películas 24 h</span><span class="chip">Música</span></div>`;
const channelCard = (n,name,initials,focus=false,heart=false) => `<article class="channel-card ${focus?'focus':''}">${live}<span class="num">${n}</span><span class="initials">${initials}</span><span class="name">${heart?'♥&nbsp; ':''}${name}</span></article>`;
const poster = (name,focus=false,heart=false) => `<article class="poster ${focus?'focus':''}">${heart?'<span class="heart">♥</span>':''}<span class="title">${name}</span></article>`;
const channelRows = (focusIndex=0,withProgram=false) => ['Noticias 24','Deportes Uno','Cine Nacional','Mundo Kids','Señal Federal','Clásicos TV','Música Sur'].map((name,i)=>`<div class="guide-row ${i===focusIndex?'focus':''}"><b class="gold">${101+i}</b><div class="logo-box">${name.split(' ').map(x=>x[0]).join('').slice(0,3)}</div><div><h3>${name}</h3><div class="hint">${['Noticias','Deportes','Películas 24 h','Infantiles','Noticias','Películas 24 h','Música'][i]}</div></div>${withProgram?`<div><b>${['Noticias del día','Partido en vivo','Cine argentino','Aventuras animadas','Panorama federal','Clásico nocturno','Sesión acústica'][i]}</b><div class="hint">${20+i}:00–${21+i}:00</div></div>`:`<div class="hint">OK · Pantalla completa</div>`}</div>`).join('');

const loginArt = `<section class="login-art"><div style="position:relative;z-index:2"><div class="brand-slot logo-ready" style="width:120px;height:100px"><img src="../brand/kairos-tv-symbol.png" alt="Kairos TV"></div><div class="eyebrow" style="margin-top:108px">Kairos TV</div><h1 style="font-size:64px;max-width:620px;margin-top:14px">Todo lo que querés ver, en el momento indicado.</h1><p class="sub" style="max-width:560px;margin-top:22px">Canales en vivo, películas y series en una experiencia pensada para tu pantalla.</p></div></section>`;
const pinpad = (focus='1') => `<div class="pinpad">${['1','2','3','4','5','6','7','8','9','Borrar','0','OK'].map(x=>`<div class="pin ${x===focus?'focus':''}">${x}</div>`).join('')}</div>`;
const tvLoginClient = bareTv('Acceso de clientes',`<div class="login-layout">${loginArt}<section class="login-card"><div class="panel"><div class="eyebrow">Acceso de clientes</div><h1 style="font-size:42px;margin-top:8px">Ingresá tu código</h1><p class="sub">Escribí los 8 números que te dio tu vendedor.</p><div class="field" style="margin-top:28px;justify-content:center"><span class="code">4821&nbsp;&nbsp;____</span></div>${pinpad('1')}<p class="hint" style="margin-top:20px;text-align:center">← ↑ ↓ → para moverte · OK para elegir</p><div class="divider"></div><button class="btn" style="width:100%">Ingresar como revendedor o administrador</button></div></section></div>`);

const tvLoginPanel = bareTv('Acceso de revendedores',`<div class="login-layout">${loginArt}<section class="login-card"><div class="panel"><div class="eyebrow">Acceso secundario</div><h1 style="font-size:42px;margin-top:8px">Revendedores y administradores</h1><p class="sub">Usá tu usuario y contraseña del panel.</p><div class="stack" style="margin-top:30px"><div class="field active focus">Usuario</div><div class="field">Contraseña</div><button class="btn primary">Ingresar al panel</button><button class="btn">Volver al acceso con código</button></div><p class="hint" style="margin-top:24px">El teclado aparece al enfocar un campo y presionar OK.</p></div></section></div>`);

const tvLoginErrors = bareTv('Estados de acceso',`<div class="safe" style="display:grid;place-items:center"><div class="panel" style="width:1180px;padding:44px"><div class="eyebrow">Acceso · Estados</div><h1 style="font-size:44px;margin:10px 0 12px">Mensajes claros, sin perder el código ingresado</h1><p class="sub">Cada error conserva el foco en la acción que permite resolverlo.</p><div class="error-list" style="margin-top:28px"><div class="error-card focus"><h3>Código incorrecto</h3><p class="sub">Revisá los 8 números e intentá nuevamente.</p><button class="btn primary">Corregir código</button></div><div class="error-card"><h3>Servicio vencido</h3><p class="sub">Tu acceso venció. Contactá a tu vendedor para renovarlo.</p><button class="btn">Ver contacto</button></div><div class="error-card"><h3>Cuenta en uso</h3><p class="sub">Esta cuenta ya está en uso en otro aparato.</p><button class="btn">Reintentar</button></div><div class="error-card"><h3>Demasiados intentos</h3><p class="sub">Esperá unos minutos antes de volver a intentar.</p><button class="btn" disabled>Reintentar en 04:32</button></div></div></div></div>`);

const tvHome = tvPage('Inicio','inicio',`${top('Inicio','Buenas noches','<button class="btn">⌕&nbsp;&nbsp;Buscar</button>')}<div class="hero"><div class="hero-copy"><div>${live}<span class="chip" style="margin-left:10px">Noticias</span></div><h1 style="margin-top:20px">Noticias 24</h1><p class="sub">Señal en vivo · Canal 101</p><div class="row" style="margin-top:25px"><button class="btn primary focus">◉&nbsp; Ver en vivo</button><button class="btn icon">♥</button><button class="btn">Abrir guía</button></div></div><div class="hero-art"><div class="hero-logo">N24</div></div></div><div class="section"><div class="section-head"><h2>Tus canales favoritos</h2><span class="hint">Ver todos →</span></div><div class="cards">${channelCard('101','Noticias 24','N24')}${channelCard('102','Deportes Uno','D1')}${channelCard('108','Cine Nacional','CN')}</div></div>`);

const tvLive = tvPage('En vivo','vivo',`${top('Televisión','En vivo','<button class="btn">▤&nbsp;&nbsp;Guía de canales</button>')} ${chips('Deportes')}<div class="section"><div class="section-head"><h2>Deportes</h2><span class="hint">Canales disponibles ahora</span></div><div class="cards">${channelCard('102','Deportes Uno','D1',true)}${channelCard('115','Fútbol Federal','FF')}${channelCard('117','Motor TV','MT')}${channelCard('121','Cancha Sur','CS')}</div></div><div class="section"><div class="section-head"><h2>Noticias</h2></div><div class="cards">${channelCard('101','Noticias 24','N24')}${channelCard('105','Señal Federal','SF')}${channelCard('109','Actualidad','ACT')}</div></div>`);

const tvGuide = tvPage('Guía de canales','guia',`${top('Televisión','Guía de canales','<button class="btn">⌕&nbsp;&nbsp;Buscar canal</button>')}<div class="guide panel" style="margin-top:16px"><aside class="guide-left"><h3>Categorías</h3><div class="stack" style="margin-top:18px"><span class="chip active">Todos</span><span class="chip">Deportes</span><span class="chip">Noticias</span><span class="chip">Infantiles</span><span class="chip">Películas 24 h</span><span class="chip">Música</span></div><div class="notice" style="margin-top:28px"><b>Sin programación</b><div class="tiny" style="margin-top:6px">La guía funciona con número, logo, nombre y categoría.</div></div></aside><section class="guide-main"><div class="row" style="justify-content:space-between;margin-bottom:10px"><span class="hint">↑ ↓ cambia el canal · OK reproduce</span><span class="hint">7 canales</span></div>${channelRows(0,false)}</section></div>`);

const tvEpg = tvPage('Guía EPG futura','guia',`${top('Televisión','Guía con programación','<span class="future">OPCIONAL · FUTURO</span>')}<div class="panel" style="margin-top:16px;padding:24px 28px;height:810px"><div class="row" style="align-items:center;margin-bottom:18px"><span class="chip active">Ahora</span><span class="chip">A continuación</span><span class="hint" style="margin-left:auto">20:00&nbsp;&nbsp;&nbsp;20:30&nbsp;&nbsp;&nbsp;21:00&nbsp;&nbsp;&nbsp;21:30</span></div>${channelRows(0,true)}<div class="notice" style="margin-top:20px">Esta variante se habilita únicamente cuando exista una fuente EPG confiable.</div></div>`,'Propuesta futura · no requiere datos actuales');

const gridPage = (type) => tvPage(type,type==='Películas'?'peliculas':'series',`${top('Catálogo',type,'<button class="btn">⌕&nbsp;&nbsp;Buscar</button>')}${chips('Todo')}<div class="section"><div class="section-head"><h2>${type==='Películas'?'Todas las películas':'Todas las series'}</h2><span class="hint">Ordenadas por disponibilidad</span></div><div class="cards">${poster('Horizonte Sur',true)}${poster('Código Aurora')}${poster('Última Estación')}${poster('Frontera')}${poster('Luz de Invierno')}${poster('Ruta 9')}</div></div>`);

const detailMovie = tvPage('Detalle de película','peliculas',`${top('Película','Detalle')}<div class="panel" style="height:790px;margin-top:18px;padding:46px;display:grid;grid-template-columns:330px 1fr;gap:50px;background:radial-gradient(circle at 78% 20%,rgba(0,240,255,.09),transparent 32%),var(--surface)"><div class="poster" style="width:300px;height:450px"><span class="title" style="font-size:30px">Horizonte Sur</span></div><div style="padding-top:36px"><span class="chip">Película</span><h1 style="margin-top:20px">Horizonte Sur</h1><p class="sub">La pantalla se sostiene con los datos disponibles: nombre, póster y categoría.</p><div class="row" style="margin-top:34px"><button class="btn primary focus">▶&nbsp; Reproducir</button><button class="btn">♥&nbsp; Agregar a favoritos</button></div><div class="divider"></div><h2>También puede interesarte</h2><div class="cards" style="margin-top:20px">${poster('Ruta 9')}${poster('Última Estación')}${poster('Luz de Invierno')}</div></div></div>`);

const detailSeries = tvPage('Detalle de serie','series',`${top('Serie','Detalle')}<div class="panel" style="height:790px;margin-top:18px;padding:38px;display:grid;grid-template-columns:270px 1fr;gap:42px"><div>${poster('Código Aurora')}<button class="btn" style="width:184px;margin-top:20px">♥ Favorito</button></div><div><h1>Código Aurora</h1><p class="sub">2 temporadas · 16 episodios</p><div class="row" style="margin-top:22px"><button class="btn primary">▶&nbsp; Continuar</button><span class="chip active">Temporada 1</span><span class="chip">Temporada 2</span></div><div class="stack" style="margin-top:28px"><div class="panel focus" style="padding:18px 22px;display:grid;grid-template-columns:110px 1fr 140px;align-items:center"><b class="gold">T1 · E1</b><div><h3>Episodio 1</h3><div class="progress" style="margin-top:10px"><i style="width:62%"></i></div></div><span class="hint">Continuar</span></div>${[2,3,4].map(i=>`<div class="panel" style="padding:18px 22px;display:grid;grid-template-columns:110px 1fr 140px;align-items:center"><b class="gold">T1 · E${i}</b><h3>Episodio ${i}</h3><span class="hint">Reproducir</span></div>`).join('')}</div></div></div>`);

const playerControls = (vod=false) => `<div class="controls glass"><div class="row" style="align-items:center"><button class="btn icon ${vod?'':'focus'}">${vod?'❚❚':'▤'}</button><div style="flex:1"><h3>${vod?'Horizonte Sur':'Noticias 24'}</h3><div class="hint">${vod?'Película':'Canal 101 · Noticias'}</div></div><button class="btn icon">♥</button><button class="btn icon">⚙</button></div>${vod?`<div class="timeline" style="margin-top:22px"><i></i></div><div class="row tiny" style="justify-content:space-between;margin-top:9px"><span>42:18</span><span>1:38:00</span></div>`:`<div class="row" style="justify-content:center;margin-top:20px"><span class="hint">↑ ↓ zapping &nbsp;·&nbsp; OK oculta controles &nbsp;·&nbsp; Atrás vuelve</span></div>`}</div>`;
const tvPlayerLive = bareTv('Reproductor en vivo',`<div class="player-bg"></div><div style="position:absolute;left:96px;top:64px;z-index:3">${live}</div>${playerControls(false)}`);
const tvPlayerVod = bareTv('Reproductor VOD',`<div class="player-bg"></div><div style="position:absolute;left:96px;top:64px;z-index:3"><span class="chip">PELÍCULA</span></div>${playerControls(true)}`);

const tvSearch = tvPage('Buscar','buscar',`${top('Catálogo','Buscar')}<div class="search focus" style="margin-top:15px">⌕&nbsp;&nbsp;noti<span style="width:2px;height:26px;background:var(--cyan);margin-left:2px"></span></div><div style="display:grid;grid-template-columns:1fr 520px;gap:34px;margin-top:32px"><section><h2>Resultados</h2><div class="stack" style="margin-top:18px"><div class="panel" style="padding:18px;display:flex;gap:18px;align-items:center"><div class="logo-box">N24</div><div><h3>Noticias 24</h3><div class="hint">Canal 101 · Noticias</div></div></div><div class="panel" style="padding:18px;display:flex;gap:18px;align-items:center"><div class="logo-box">SF</div><div><h3>Señal Federal Noticias</h3><div class="hint">Canal 105 · Noticias</div></div></div></div></section><section><h2>Teclado</h2><div class="keyboard" style="margin-top:18px">${'ABCDEFGHIJKLMNÑOPQRSTUVWXYZ'.split('').map(x=>`<div class="key">${x}</div>`).join('')}<div class="key wide">Borrar</div><div class="key space">Espacio</div><div class="key wide">Listo</div></div></section></div>`);

const tvFavorites = tvPage('Favoritos','favoritos',`${top('Tu biblioteca','Favoritos')}<div class="section"><div class="section-head"><h2>Canales</h2><span class="hint">OK largo sobre una tarjeta para quitar</span></div><div class="cards">${channelCard('101','Noticias 24','N24',true,true)}${channelCard('102','Deportes Uno','D1',false,true)}${channelCard('108','Cine Nacional','CN',false,true)}</div></div><div class="section"><div class="section-head"><h2>Películas y series</h2></div><div class="cards">${poster('Horizonte Sur',false,true)}${poster('Código Aurora',false,true)}${poster('Ruta 9',false,true)}</div></div>`);

const tvAccount = tvPage('Mi cuenta','cuenta',`${top('Perfil','Mi cuenta')}<div style="display:grid;grid-template-columns:1.1fr .9fr;gap:28px;margin-top:25px"><section class="panel" style="padding:34px"><div class="row" style="align-items:center"><div style="width:90px;height:90px;border-radius:50%;background:var(--cyan);color:var(--cyan-ink);display:grid;place-items:center;font:800 30px Jakarta">MS</div><div><h2>María Silva</h2><p class="sub" style="margin:4px 0">Cliente</p></div></div><div class="divider"></div><div class="stack"><div><span class="hint">Código de acceso</span><h3>4821 9037</h3></div><div><span class="hint">Servicio vigente hasta</span><h3>18 de octubre de 2026</h3></div><div><span class="hint">Pantallas</span><h3>1 de 2 en uso</h3></div></div></section><section class="panel" style="padding:34px"><h2>Preferencias</h2><div class="stack" style="margin-top:24px"><button class="btn focus">Volver al último canal al abrir</button><button class="btn">Administrar favoritos</button><button class="btn">Buscar actualizaciones</button><button class="btn">Cerrar sesión</button></div></section></div>`);

const tvExpired = bareTv('Servicio vencido',`<div class="safe center"><div class="panel" style="width:760px;padding:48px"><div style="font-size:62px;color:var(--ruby)">◷</div><div class="eyebrow" style="color:var(--ruby-light);margin-top:12px">Servicio vencido</div><h1 style="font-size:48px;margin-top:8px">Tu servicio venció</h1><p class="sub">Contactá a tu vendedor para renovarlo y volver a mirar Kairos TV.</p><div class="panel" style="padding:22px;margin:28px 0;text-align:left"><span class="hint">Contacto configurado por tu vendedor</span><h3 style="margin-top:8px">Soporte de tu servicio</h3></div><button class="btn primary focus" style="width:100%">Contactar a mi vendedor</button><button class="btn" style="width:100%;margin-top:14px">Volver a intentar</button></div></div>`);

const tvUpdate = bareTv('Actualización',`<div class="safe center"><div class="panel" style="width:820px;padding:46px;text-align:left"><span class="chip active">NUEVA VERSIÓN</span><h1 style="font-size:48px;margin-top:18px">Hay una versión nueva</h1><p class="sub">Mejoras incluidas:</p><ul class="sub" style="line-height:2"><li>Guía de canales más rápida</li><li>Favoritos separados por tipo</li><li>Mejor recuperación cuando falla una señal</li></ul><div class="progress" style="margin:28px 0 10px;height:10px"><i style="width:68%"></i></div><div class="row" style="justify-content:space-between"><span class="hint">Descargando… 68 %</span><span class="hint">42 MB de 62 MB</span></div><button class="btn primary focus" style="width:100%;margin-top:28px">Actualizar</button></div></div>`);

const tvSignalError = bareTv('Recuperación de señal',`<div class="player-bg"></div><div class="modal-backdrop"><div class="modal center"><div style="font-size:56px;color:var(--cyan)">⌁</div><h1 style="font-size:40px;margin-top:12px">Este canal no está disponible</h1><p class="sub">La señal se interrumpió. Estamos probando otra fuente automáticamente…</p><div class="progress" style="width:100%;margin:25px 0"><i style="width:55%"></i></div><div class="row"><button class="btn primary focus">Probar de nuevo</button><button class="btn">Volver a la guía</button></div></div></div>`);

const tvExit = tvPage('Salir','inicio',`${top('Inicio','Kairos TV')}<div class="modal-backdrop" style="inset:-62px -96px -58px -152px"><div class="modal"><h1 style="font-size:42px">¿Querés salir de Kairos TV?</h1><p class="sub">Podés volver al último canal cuando abras la app nuevamente.</p><div class="row" style="margin-top:30px"><button class="btn primary focus" style="flex:1">Seguir mirando</button><button class="btn" style="flex:1">Salir</button></div></div></div>`);

const mobileNav = (active='inicio') => `<nav class="mobile-nav"><span class="${active==='inicio'?'active':''}"><b>⌂</b>Inicio</span><span class="${active==='vivo'?'active':''}"><b>◉</b>En vivo</span><span><b>▦</b>Series</span><span><b>▰</b>Películas</span><span class="${active==='favoritos'?'active':''}"><b>♥</b>Favoritos</span><span><b>●</b>Mi espacio</span></nav>`;
const mobileTop = (title) => `<header class="mobile-top"><div class="brand-slot logo-ready" style="width:42px;height:36px;margin:0"><img src="../brand/kairos-tv-symbol.png" alt="Kairos TV"></div><b class="eyebrow">${title}</b><span style="font-size:21px">⌕</span></header>`;
const mobilePage = (title,active,content) => `${head(title)}<main class="mobile relative overflow-hidden bg-[#131317] text-[#E4E1E8]">${mobileTop(title)}<section class="mobile-content">${content}</section>${mobileNav(active)}</main></body></html>`;
const bareMobile = (title,content) => `${head(title)}<main class="mobile relative overflow-hidden bg-[#131317] text-[#E4E1E8]">${content}</main></body></html>`;

const mobileLogin = bareMobile('Acceso de clientes',`<div class="m-login"><div class="brand-slot logo-ready" style="width:74px;height:74px;margin:0 auto 34px"><img src="../brand/kairos-tv-symbol.png" alt="Kairos TV"></div><div class="eyebrow">Acceso de clientes</div><h1 class="m-title" style="margin-top:8px">Ingresá tu código</h1><p class="m-sub">Los 8 números que te dio tu vendedor.</p><div class="m-field" style="justify-content:center;margin:24px 0;font:800 22px Jakarta;letter-spacing:.16em;color:var(--cyan-light)">4821&nbsp; ____</div><div class="m-pinpad">${['1','2','3','4','5','6','7','8','9','⌫','0','OK'].map((x,i)=>`<div class="m-pin ${i===0?'focus':''}">${x}</div>`).join('')}</div><button class="m-btn" style="width:100%;margin-top:20px">Revendedores / administradores</button></div>`);
const mobileAdmin = bareMobile('Acceso al panel',`<div class="m-login"><div class="brand-slot logo-ready" style="width:74px;height:74px;margin:0 auto 34px"><img src="../brand/kairos-tv-symbol.png" alt="Kairos TV"></div><div class="eyebrow">Acceso secundario</div><h1 class="m-title" style="margin-top:8px">Revendedores y administradores</h1><p class="m-sub">Ingresá con tu cuenta del panel.</p><div class="stack" style="margin-top:24px"><div class="m-field focus">Usuario</div><div class="m-field">Contraseña</div><button class="m-btn primary">Ingresar</button><button class="m-btn">Volver al código de cliente</button></div></div>`);
const mobileErrors = bareMobile('Errores de acceso',`<div class="m-login" style="padding-top:34px"><div class="eyebrow">Acceso · Estados</div><h1 class="m-title" style="margin:8px 0 18px">Si algo sale mal</h1><div class="stack"><div class="alert focus"><b>Código incorrecto</b><div class="tiny" style="margin-top:4px">Revisá los 8 números.</div></div><div class="alert"><b>Servicio vencido</b><div class="tiny" style="margin-top:4px">Contactá a tu vendedor.</div></div><div class="alert"><b>Cuenta en uso</b><div class="tiny" style="margin-top:4px">Ya está abierta en otro aparato.</div></div><div class="alert"><b>Demasiados intentos</b><div class="tiny" style="margin-top:4px">Volvé a probar en 04:32.</div></div></div><button class="m-btn primary" style="width:100%;margin-top:20px">Corregir código</button></div>`);

const mobileHome = mobilePage('Inicio','inicio',`<div class="m-card" style="height:250px;padding:18px;background:radial-gradient(circle at 75% 22%,rgba(0,240,255,.18),transparent 28%),linear-gradient(150deg,#11282e,var(--deep));display:flex;flex-direction:column;justify-content:end"><div>${live}</div><h1 class="m-title" style="margin-top:10px">Noticias 24</h1><p class="m-sub">Canal 101 · Noticias</p><button class="m-btn primary" style="margin-top:10px">Ver en vivo</button></div><h3 style="margin:20px 0 12px">Tus canales favoritos</h3><div class="m-row"><div class="m-channel"><span class="m-badge">EN VIVO</span><h3 style="margin-top:35px">N24</h3><span class="tiny">Noticias 24</span></div><div class="m-channel"><span class="m-badge">EN VIVO</span><h3 style="margin-top:35px">D1</h3><span class="tiny">Deportes Uno</span></div></div><h3 style="margin:20px 0 12px">Directos destacados</h3><div class="m-row"><div class="m-channel"><span class="m-badge">EN VIVO</span><h3 style="margin-top:35px">CN</h3><span class="tiny">Cine Nacional</span></div><div class="m-channel"><span class="m-badge">EN VIVO</span><h3 style="margin-top:35px">MK</h3><span class="tiny">Mundo Kids</span></div></div>`);

const mobileGuide = mobilePage('Guía','vivo',`<div class="search" style="height:48px">⌕&nbsp; Buscar canal</div><div class="row" style="gap:8px;margin:14px 0;overflow:hidden"><span class="chip active" style="height:36px">Todos</span><span class="chip" style="height:36px">Deportes</span><span class="chip" style="height:36px">Noticias</span></div><div class="m-card" style="padding:0 12px">${['Noticias 24','Deportes Uno','Cine Nacional','Mundo Kids','Señal Federal','Clásicos TV','Música Sur','Actualidad'].map((n,i)=>`<div class="m-guide-row ${i===0?'focus':''}"><b class="gold tiny">${101+i}</b><span class="placeholder-logo">${n.split(' ').map(x=>x[0]).join('').slice(0,2)}</span><div><b class="tiny">${n}</b><div class="tiny dim">${['Noticias','Deportes','Películas','Infantiles'][i%4]}</div></div><span>›</span></div>`).join('')}</div>`);

const mobileFavorites = mobilePage('Favoritos','favoritos',`<h1 class="m-title">Favoritos</h1><p class="m-sub">Todo lo que más mirás, separado por tipo.</p><h3 style="margin:20px 0 12px">Canales</h3><div class="m-row"><div class="m-channel focus"><span class="heart">♥</span><h3 style="margin-top:45px">N24</h3><span class="tiny">Noticias 24</span></div><div class="m-channel"><h3 style="margin-top:45px">D1</h3><span class="tiny">Deportes Uno</span></div></div><h3 style="margin:22px 0 12px">Películas</h3><div class="m-row"><div class="m-poster">Horizonte Sur</div><div class="m-poster">Ruta 9</div><div class="m-poster">Frontera</div></div><h3 style="margin:22px 0 12px">Series</h3><div class="m-row"><div class="m-poster">Código Aurora</div><div class="m-poster">Última Estación</div></div>`);

const mobileExpired = bareMobile('Servicio vencido',`<div class="m-login center"><div><div style="font-size:54px;color:var(--ruby)">◷</div><div class="eyebrow ruby" style="margin-top:12px">Servicio vencido</div><h1 class="m-title" style="margin-top:8px">Tu servicio venció</h1><p class="m-sub">Contactá a tu vendedor para volver a mirar Kairos TV.</p><div class="m-card" style="padding:18px;text-align:left;margin:24px 0"><span class="tiny dim">Contacto configurado</span><h3 style="margin-top:6px">Soporte de tu servicio</h3></div><button class="m-btn primary focus" style="width:100%">Contactar a mi vendedor</button><button class="m-btn" style="width:100%;margin-top:12px">Volver a intentar</button></div></div>`);

const mobileUpdate = bareMobile('Actualización',`<div class="m-login"><span class="chip active">NUEVA VERSIÓN</span><h1 class="m-title" style="margin-top:18px">Hay una versión nueva</h1><p class="m-sub">Mejoras incluidas:</p><div class="m-card" style="padding:18px;margin-top:18px"><div class="stack tiny"><span>✓ Guía de canales más rápida</span><span>✓ Favoritos separados por tipo</span><span>✓ Recuperación de señales mejorada</span></div></div><div class="progress" style="margin-top:30px"><i style="width:68%"></i></div><div class="row tiny dim" style="justify-content:space-between;margin-top:8px"><span>Descargando… 68 %</span><span>42 MB / 62 MB</span></div><button class="m-btn primary focus" style="width:100%;margin-top:28px">Actualizar</button><button class="m-btn" style="width:100%;margin-top:12px">Más tarde</button></div>`);

const tvFavoritesEmpty = tvPage('Favoritos vacíos','favoritos',`${top('Tu biblioteca','Favoritos')}<div class="panel center" style="height:720px;margin-top:24px"><div style="max-width:620px"><div style="font-size:68px;color:var(--ruby-light)">♡</div><h1 style="font-size:44px;margin-top:15px">Todavía no tenés favoritos</h1><p class="sub">Guardá canales, películas y series con el corazón. En TV también podés mantener OK sobre cualquier tarjeta.</p><button class="btn primary focus" style="margin-top:22px">Explorar contenido</button></div></div>`);
const tvLoading = bareTv('Pantalla de carga',`<div class="safe center"><div><div class="brand-slot logo-ready" style="width:170px;height:150px;margin:0 auto 38px"><img src="../brand/kairos-tv-symbol.png" alt="Kairos TV"></div><div style="width:82px;height:82px;border-radius:50%;border:7px solid var(--high);border-top-color:var(--cyan);margin:0 auto;box-shadow:0 0 28px rgba(0,240,255,.24)"></div><h1 style="font-size:38px;margin-top:30px">Preparando tus canales</h1><p class="sub">Un momento…</p></div></div>`);
const mobileFavoritesEmpty = mobilePage('Favoritos','favoritos',`<div class="center" style="height:100%"><div><div style="font-size:58px;color:var(--ruby-light)">♡</div><h1 class="m-title" style="margin-top:12px">Todavía no tenés favoritos</h1><p class="m-sub">Tocá el corazón de tus canales, películas y series para encontrarlos acá.</p><button class="m-btn primary" style="width:100%;margin-top:20px">Explorar contenido</button></div></div>`);
const mobileLoading = bareMobile('Pantalla de carga',`<div class="center" style="height:100%;padding:24px"><div><div class="brand-slot logo-ready" style="width:104px;height:92px;margin:0 auto 30px"><img src="../brand/kairos-tv-symbol.png" alt="Kairos TV"></div><div style="width:58px;height:58px;border-radius:50%;border:5px solid var(--high);border-top-color:var(--cyan);margin:0 auto"></div><h1 class="m-title" style="margin-top:24px">Preparando tus canales</h1><p class="m-sub">Un momento…</p></div></div>`);

const pages = {
  'tv-01-login-cliente': tvLoginClient,
  'tv-02-login-panel': tvLoginPanel,
  'tv-03-login-errores': tvLoginErrors,
  'tv-04-inicio': tvHome,
  'tv-05-en-vivo': tvLive,
  'tv-06-guia-canales': tvGuide,
  'tv-07-guia-epg-futura': tvEpg,
  'tv-08-peliculas': gridPage('Películas'),
  'tv-09-series': gridPage('Series'),
  'tv-10-detalle-pelicula': detailMovie,
  'tv-11-detalle-serie': detailSeries,
  'tv-12-reproductor-vivo': tvPlayerLive,
  'tv-13-reproductor-vod': tvPlayerVod,
  'tv-14-buscar': tvSearch,
  'tv-15-favoritos': tvFavorites,
  'tv-16-mi-cuenta': tvAccount,
  'tv-17-servicio-vencido': tvExpired,
  'tv-18-actualizacion': tvUpdate,
  'tv-19-error-senal': tvSignalError,
  'tv-20-salir': tvExit,
  'tv-21-favoritos-vacio': tvFavoritesEmpty,
  'tv-22-carga': tvLoading,
  'mobile-01-login-cliente': mobileLogin,
  'mobile-02-login-panel': mobileAdmin,
  'mobile-03-login-errores': mobileErrors,
  'mobile-04-inicio-vivo': mobileHome,
  'mobile-05-guia-canales': mobileGuide,
  'mobile-06-favoritos': mobileFavorites,
  'mobile-07-servicio-vencido': mobileExpired,
  'mobile-08-actualizacion': mobileUpdate,
  'mobile-09-favoritos-vacio': mobileFavoritesEmpty,
  'mobile-10-carga': mobileLoading,
};

for (const [name, html] of Object.entries(pages)) fs.writeFileSync(path.join(out, `${name}.html`), html, 'utf8');
console.log(`Generadas ${Object.keys(pages).length} pantallas en ${out}`);
