# Generated by Django 6.1.1 on 2026-09-30 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario_texto', models.CharField(blank=True, max_length=150, verbose_name='usuario')),
                ('accion', models.CharField(choices=[('ingreso', 'Ingresó al sistema'), ('ingreso_fallido', 'Intento de ingreso fallido'), ('salida', 'Cerró sesión'), ('crear', 'Creó'), ('editar', 'Editó'), ('eliminar', 'Eliminó'), ('seguridad', 'Seguridad'), ('sistema', 'Sistema'), ('otro', 'Otro')], db_index=True, max_length=20)),
                ('modulo', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='módulo')),
                ('descripcion', models.CharField(max_length=300, verbose_name='descripción')),
                ('objeto_tipo', models.CharField(blank=True, max_length=100)),
                ('objeto_id', models.CharField(blank=True, max_length=50)),
                ('objeto_texto', models.CharField(blank=True, max_length=200)),
                ('cambios', models.JSONField(blank=True, default=dict)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registro de actividad',
                'verbose_name_plural': 'registro de actividad',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['objeto_tipo', 'objeto_id'], name='actividad_r_objeto__940d0f_idx')],
            },
        ),
    ]
